### ISSUE TITLE
Rendering depends of devices?

### ISSUE THREAD

**Issue by benjaminbarbe** [KalebKE/GyroscopeExplorer#1]
Hi all,

Thanks for your good example.
But when I launch this application on two different devices, the axis are inverted...

1. Samsung galaxy tab s2 (SM-T810): works like a charm
2. Samsung Galaxy Tab Pro 10.1 LTE (SM-T525)

Any idea?

**Comment by benjaminbarbe** [comment]
To respond to my own question:

I believe getRotationMatrix() returns a rotation matrix that converts device coordinate to world coordinate, as mentioned in android documentation, not "world" to "device".

```
Computes the inclination matrix I as well as the rotation matrix R transforming a vector from the device coordinate system to the world's coordinate system which is defined as a direct orthonormal basis
```

You need to use: ```SensorManager.remapCoordinateSystem```

**Comment by KEOpenSource** [comment]
@benjaminbarbe Would you mind submitting a pull request?

**Comment by KalebKE** [comment]
> To elaborate on this, using SensorManager.remapCoordinateSystem will allow you to remap the coordinate system on devices that have an inverted axis, but how do you know what devices need to have the coordinate system remapped? Superficially, this seems like a manufacturer specific error that really can't be fixed in code. Do you agree?

@ghost This is a correct analysis.
