### ISSUE TITLE
How do I calibrate the gyroscope？

### ISSUE THREAD

**Issue by hewking** [KalebKE/GyroscopeExplorer#2]
Now I have a requirement，
The gyroscope horizontally on the desktop automatically calibrates，after the transfer of data to calibrate my application?

**Comment by KalebKE** [comment]
@hewking 

Gyroscope Explorer does not calibrate your devices gyroscope. You will need to implement the calibrations in your application. Generally, calibration is done automatically by the Android implementation when using [TYPE_GYROSCOPE)](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_GYROSCOPE). If TYPE_GYROSCOPE is not sufficient, you will have to implement your own calibration algorithm using [TYPE_GYROSCOPE_UNCALIBRATED](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_GYROSCOPE_UNCALIBRATED) and the appropriate sensor fusions.
