### ISSUE TITLE
Licence Change. 

### ISSUE THREAD

**Issue by icyield** [KalebKE/GyroscopeExplorer#5]
Hi. I see you changed/added the project license. The files in the project still have the old license text. Are these files still, 

/*
 * Gyroscope Explorer
 * Copyright (C) 2013-2015, Kaleb Kircher - Kircher Engineering, LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

Or under the Apache License. 

Regards. And Good work, thanks.

**Comment by KalebKE** [comment]
Thank you for pointing this out. Updated and resolved.
